# Generated by Django 3.2.4 on 2021-06-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_ordered', models.DateTimeField(auto_now_add=True)),
                ('Complete', models.BooleanField(default=False, null=True)),
                ('Customer_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customerregister')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItem', models.AutoField(primary_key=True, serialize=False)),
                ('Qty', models.IntegerField(default=0)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
                ('Product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
    ]
