# Generated by Django 3.2.4 on 2021-06-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderitem_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('ShippingAddress_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('num', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Customer_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customerregister')),
                ('OrderItem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderitem')),
            ],
        ),
    ]
